services:
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  web:
    build: .
    ports:
      - "8000:8000"
      - "9023:9023"
    volumes:
      - .:/app
    environment:
      - MONGODB_URL=mongodb://mongodb:27018
      - MONGODB_DB=catalogs_db
      - DEBUG=True
    depends_on:
      - mongodb
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge
