services:
  web:
    build: .
    ports:
      - "8000:8000"
      - "9023:9023"
    volumes:
      - .:/app
    environment:
      - .env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
