services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_network
    environment:
      - HOST=0.0.0.0

networks:
  app_network:
    driver: bridge
